"""
Data Protection Sentinel — Excel (xlsx) export for RoPA.
Produces a professional multi-sheet workbook matching sample quality.
"""
import io
import json
from datetime import datetime

try:
    from openpyxl import Workbook
    from openpyxl.styles import (
        PatternFill, Font, Alignment, Border, Side,
        GradientFill
    )
    from openpyxl.utils import get_column_letter
    OPENPYXL_AVAILABLE = True
except ImportError:
    OPENPYXL_AVAILABLE = False

# ── Brand colours ──────────────────────────────────────────────────────────────
C_DARK_GREEN   = "166534"
C_MID_GREEN    = "15803d"
C_LIGHT_GREEN  = "dcfce7"
C_ACCENT       = "f0fdf4"
C_HEADER_TEXT  = "FFFFFF"
C_SUBHEADER    = "374151"
C_TEXT         = "111827"
C_GREY         = "6b7280"
C_BORDER       = "e5e7eb"
C_ALT_ROW      = "f9fafb"
C_RISK_VH      = "fee2e2"
C_RISK_H       = "fef3c7"
C_RISK_M       = "fef9c3"
C_RISK_L       = "dcfce7"

RISK_FILL = {
    "critical": PatternFill("solid", fgColor=C_RISK_VH),
    "very high": PatternFill("solid", fgColor=C_RISK_VH),
    "high":      PatternFill("solid", fgColor=C_RISK_H),
    "medium":    PatternFill("solid", fgColor=C_RISK_M),
    "low":       PatternFill("solid", fgColor=C_RISK_L),
}

def _thin_border():
    s = Side(style="thin", color=C_BORDER)
    return Border(left=s, right=s, top=s, bottom=s)


def _header_style(bold=True, size=10, color=C_HEADER_TEXT, bg=C_DARK_GREEN, wrap=True, center=False):
    return {
        "font": Font(name="Calibri", bold=bold, size=size, color=color),
        "fill": PatternFill("solid", fgColor=bg),
        "alignment": Alignment(horizontal="center" if center else "left",
                               vertical="center", wrap_text=wrap),
        "border": _thin_border(),
    }


def _cell_style(bold=False, size=10, color=C_TEXT, bg="FFFFFF", wrap=True, center=False):
    return {
        "font": Font(name="Calibri", bold=bold, size=size, color=color),
        "fill": PatternFill("solid", fgColor=bg),
        "alignment": Alignment(horizontal="center" if center else "left",
                               vertical="center", wrap_text=wrap),
        "border": _thin_border(),
    }


def _apply(cell, styles):
    for attr, val in styles.items():
        setattr(cell, attr, val)


def _safe(val, default="—"):
    if val is None:
        return default
    if isinstance(val, list):
        return ", ".join(str(v) for v in val) if val else default
    s = str(val).strip()
    if s in ("", "null", "None", "[]", "{}"):
        return default
    # Try to parse JSON list
    if s.startswith("["):
        try:
            lst = json.loads(s)
            if isinstance(lst, list):
                return ", ".join(str(i) for i in lst) if lst else default
        except Exception:
            pass
    return s


def generate_ropa_xlsx(entries, settings=None):
    """
    Generate a professional RoPA Excel workbook.
    entries: list of dicts from db.list_ropa()
    settings: dict of org settings
    Returns: BytesIO buffer
    """
    if not OPENPYXL_AVAILABLE:
        raise RuntimeError("openpyxl not installed. Run: pip install openpyxl")

    settings = settings or {}
    wb = Workbook()

    # ── Sheet 1: Cover ──────────────────────────────────────────────────────
    ws_cover = wb.active
    ws_cover.title = "Cover"
    ws_cover.sheet_view.showGridLines = False
    ws_cover.column_dimensions["A"].width = 4
    ws_cover.column_dimensions["B"].width = 30
    ws_cover.column_dimensions["C"].width = 40
    ws_cover.row_dimensions[1].height = 8

    # Header banner
    for row in range(2, 7):
        ws_cover.row_dimensions[row].height = 18
    ws_cover.merge_cells("B2:C6")
    banner = ws_cover["B2"]
    banner.value = "DATA PROTECTION SENTINEL"
    _apply(banner, {
        "font": Font(name="Calibri", bold=True, size=26, color=C_HEADER_TEXT),
        "fill": PatternFill("solid", fgColor=C_DARK_GREEN),
        "alignment": Alignment(horizontal="center", vertical="center"),
    })

    ws_cover.row_dimensions[7].height = 20
    ws_cover.merge_cells("B7:C7")
    sub = ws_cover["B7"]
    sub.value = "Record of Processing Activities (RoPA)"
    _apply(sub, {
        "font": Font(name="Calibri", size=14, italic=True, color=C_DARK_GREEN),
        "fill": PatternFill("solid", fgColor=C_ACCENT),
        "alignment": Alignment(horizontal="center", vertical="center"),
    })

    ws_cover.row_dimensions[8].height = 6

    meta_rows = [
        ("Organisation:", settings.get("org_name", "—")),
        ("Country:", settings.get("org_country", "—")),
        ("DPO Name:", settings.get("dpo_name", "—")),
        ("DPO Email:", settings.get("dpo_email", "—")),
        ("Primary Regulation:", settings.get("primary_regulation", "—")),
        ("Export Date:", datetime.utcnow().strftime("%d %B %Y")),
        ("Total Activities:", str(len(entries))),
        ("Generated By:", "Data Protection Sentinel · by Ali Moyo"),
    ]
    for i, (label, value) in enumerate(meta_rows, start=9):
        ws_cover.row_dimensions[i].height = 18
        lc = ws_cover.cell(row=i, column=2, value=label)
        _apply(lc, {
            "font": Font(name="Calibri", bold=True, size=10, color=C_DARK_GREEN),
            "fill": PatternFill("solid", fgColor=C_ACCENT),
            "border": _thin_border(),
            "alignment": Alignment(vertical="center"),
        })
        vc = ws_cover.cell(row=i, column=3, value=value)
        _apply(vc, {
            "font": Font(name="Calibri", size=10, color=C_TEXT),
            "fill": PatternFill("solid", fgColor="FFFFFF"),
            "border": _thin_border(),
            "alignment": Alignment(vertical="center"),
        })

    ws_cover.row_dimensions[19].height = 10
    note_row = 20
    ws_cover.merge_cells(f"B{note_row}:C{note_row}")
    note = ws_cover.cell(row=note_row, column=2, value="CONFIDENTIAL — For authorised personnel only")
    _apply(note, {
        "font": Font(name="Calibri", size=9, italic=True, color=C_GREY),
        "alignment": Alignment(horizontal="center"),
    })

    # ── Sheet 2: RoPA Register ───────────────────────────────────────────────
    ws = wb.create_sheet("RoPA Register")
    ws.sheet_view.showGridLines = False
    ws.freeze_panes = "A3"

    COLUMNS = [
        ("ID",                  8),
        ("Ref No.",             14),
        ("Activity Name",       30),
        ("Department",          16),
        ("Owner",               16),
        ("Controller",          20),
        ("DPO Name",            18),
        ("DPO Email",           24),
        ("Purpose",             28),
        ("Regulation",          18),
        ("Legal Basis",         30),
        ("Data Categories",     28),
        ("Special Categories",  22),
        ("Data Subjects",       18),
        ("Subject Count",       14),
        ("Retention Period",    18),
        ("Recipients",          20),
        ("Intl Transfer",       14),
        ("Transfer Dest.",      18),
        ("Risk Level",          12),
        ("DPIA Required",       14),
        ("Status",              12),
        ("Review Date",         14),
        ("Created",             14),
        ("Updated",             14),
    ]

    # Title row
    ws.merge_cells(f"A1:{get_column_letter(len(COLUMNS))}1")
    title_cell = ws["A1"]
    title_cell.value = f"Record of Processing Activities — {settings.get('org_name','Organisation')} — {datetime.utcnow().strftime('%d %B %Y')}"
    _apply(title_cell, {
        "font": Font(name="Calibri", bold=True, size=12, color=C_HEADER_TEXT),
        "fill": PatternFill("solid", fgColor=C_DARK_GREEN),
        "alignment": Alignment(horizontal="center", vertical="center"),
    })
    ws.row_dimensions[1].height = 22

    # Header row
    ws.row_dimensions[2].height = 28
    for col_idx, (col_name, col_width) in enumerate(COLUMNS, start=1):
        cell = ws.cell(row=2, column=col_idx, value=col_name)
        _apply(cell, _header_style(center=True))
        ws.column_dimensions[get_column_letter(col_idx)].width = col_width

    # Data rows
    for row_idx, entry in enumerate(entries, start=3):
        bg = "FFFFFF" if row_idx % 2 == 1 else C_ALT_ROW
        risk = _safe(entry.get("risk_score"), "low").lower()
        risk_fill = RISK_FILL.get(risk, PatternFill("solid", fgColor=bg))

        row_data = [
            str(entry.get("id", "")),
            _safe(entry.get("ref_number")),
            _safe(entry.get("processing_name")),
            _safe(entry.get("department")),
            _safe(entry.get("owner")),
            _safe(entry.get("controller_name")),
            _safe(entry.get("dpo_name")),
            _safe(entry.get("dpo_email")),
            _safe(entry.get("purpose")),
            _safe(entry.get("regulation")),
            _safe(entry.get("legal_basis")),
            _safe(entry.get("data_categories")),
            _safe(entry.get("special_categories")),
            _safe(entry.get("data_subjects")),
            _safe(entry.get("subject_count")),
            _safe(entry.get("retention_period")),
            _safe(entry.get("recipients")),
            _safe(entry.get("intl_transfers")),
            _safe(entry.get("transfer_dest")),
            _safe(entry.get("risk_score")).title(),
            "Yes" if entry.get("dpia_required") else "No",
            _safe(entry.get("status"), "active").replace("_", " ").title(),
            _safe(entry.get("review_date")),
            _safe(entry.get("created_at", ""))[:10],
            _safe(entry.get("updated_at", ""))[:10],
        ]
        ws.row_dimensions[row_idx].height = 16
        for col_idx, value in enumerate(row_data, start=1):
            cell = ws.cell(row=row_idx, column=col_idx, value=value)
            # Risk column gets colour-coded
            if col_idx == 20:  # Risk Level column
                _apply(cell, {
                    "font": Font(name="Calibri", bold=True, size=9, color=C_TEXT),
                    "fill": risk_fill,
                    "alignment": Alignment(horizontal="center", vertical="center"),
                    "border": _thin_border(),
                })
            else:
                _apply(cell, _cell_style(bg=bg, size=9))

    # Auto-filter
    ws.auto_filter.ref = f"A2:{get_column_letter(len(COLUMNS))}{len(entries)+2}"

    # ── Sheet 3: Controllers ─────────────────────────────────────────────────
    # Placeholder: could be expanded with controller data
    ws_ctrl = wb.create_sheet("Summary")
    ws_ctrl.sheet_view.showGridLines = False
    ws_ctrl.column_dimensions["A"].width = 4
    ws_ctrl.column_dimensions["B"].width = 30
    ws_ctrl.column_dimensions["C"].width = 15
    ws_ctrl.column_dimensions["D"].width = 15
    ws_ctrl.column_dimensions["E"].width = 15
    ws_ctrl.column_dimensions["F"].width = 15

    ws_ctrl.merge_cells("B2:F2")
    hdr = ws_ctrl["B2"]
    hdr.value = "RoPA Summary Statistics"
    _apply(hdr, {
        "font": Font(name="Calibri", bold=True, size=14, color=C_HEADER_TEXT),
        "fill": PatternFill("solid", fgColor=C_MID_GREEN),
        "alignment": Alignment(horizontal="center", vertical="center"),
    })
    ws_ctrl.row_dimensions[2].height = 24

    # Count by risk
    from collections import Counter
    risk_counts = Counter(str(e.get("risk_score","low")).lower() for e in entries)
    reg_counts = Counter(str(e.get("regulation","")) for e in entries)
    dpia_count = sum(1 for e in entries if e.get("dpia_required"))
    intl_count = sum(1 for e in entries if str(e.get("intl_transfers","")).lower() == "yes")

    summary_data = [
        ("Total Processing Activities", len(entries), ""),
        ("DPIA Required", dpia_count, f"{round(dpia_count/len(entries)*100 if entries else 0)}%"),
        ("International Transfers", intl_count, f"{round(intl_count/len(entries)*100 if entries else 0)}%"),
        ("", "", ""),
        ("Risk Breakdown", "", ""),
        ("  Critical / Very High", risk_counts.get("critical",0) + risk_counts.get("very high",0), ""),
        ("  High", risk_counts.get("high",0), ""),
        ("  Medium", risk_counts.get("medium",0), ""),
        ("  Low", risk_counts.get("low",0), ""),
        ("", "", ""),
        ("Top Regulations", "", ""),
    ]
    for code, count in reg_counts.most_common(10):
        summary_data.append((f"  {code}", count, ""))

    for i, (label, val, extra) in enumerate(summary_data, start=4):
        ws_ctrl.row_dimensions[i].height = 16
        lc = ws_ctrl.cell(row=i, column=2, value=label)
        vc = ws_ctrl.cell(row=i, column=3, value=val if val != "" else "")
        ec = ws_ctrl.cell(row=i, column=4, value=extra if extra != "" else "")
        is_section = not str(label).startswith("  ") and label not in ("", )
        bg = C_ACCENT if is_section else ("FFFFFF" if i % 2 else C_ALT_ROW)
        _apply(lc, {
            "font": Font(name="Calibri", bold=is_section, size=10, color=C_DARK_GREEN if is_section else C_TEXT),
            "fill": PatternFill("solid", fgColor=bg),
            "border": _thin_border(),
            "alignment": Alignment(vertical="center"),
        })
        _apply(vc, {
            "font": Font(name="Calibri", bold=is_section, size=10, color=C_TEXT),
            "fill": PatternFill("solid", fgColor=bg),
            "border": _thin_border(),
            "alignment": Alignment(horizontal="center", vertical="center"),
        })
        _apply(ec, {
            "font": Font(name="Calibri", size=9, color=C_GREY),
            "fill": PatternFill("solid", fgColor=bg),
            "border": _thin_border(),
            "alignment": Alignment(horizontal="center", vertical="center"),
        })

    ws_ctrl.cell(row=len(summary_data)+8, column=2,
                 value=f"Generated by Data Protection Sentinel · by Ali Moyo · {datetime.utcnow().strftime('%d %B %Y')}").font = Font(name="Calibri", size=8, italic=True, color=C_GREY)

    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    return buf
