"""
Download the Google Fonts referenced across ThemisIQ templates and emit a
self-hosted /static/fonts/fonts.css that uses local WOFF2 files.

Run once at deploy time (or rerun when font weights change):

    python scripts/fetch_fonts.py

It writes:
    static/fonts/<family>-<weight>.woff2     (one file per weight)
    static/fonts/fonts.css                   (the @font-face stylesheet)

We pretend to be Chrome so Google serves WOFF2 (not TTF/OTF). Latin subset
only: that's what every UI string on the platform uses today.
"""
import re
import sys
import urllib.request
from pathlib import Path

FONTS = {
    # family-name : list of weights to include
    "Plus Jakarta Sans":  [400, 500, 600, 700, 800],
    "JetBrains Mono":     [400, 500],
    "Inter":              [400, 500, 600, 700, 800, 900],
    "DM Sans":            [400, 500, 600, 700],
    "Space Grotesk":      [400, 500, 600, 700],
    "Cormorant Garamond": [400, 500, 600],
}

OUT_DIR = Path(__file__).resolve().parent.parent / "static" / "fonts"

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")


def build_request_url(family: str, weights: list[int]) -> str:
    family_q = family.replace(" ", "+")
    weights_q = ";".join(str(w) for w in weights)
    return (
        "https://fonts.googleapis.com/css2?"
        f"family={family_q}:wght@{weights_q}&display=swap"
    )


def http_get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read()


def slug(family: str) -> str:
    return family.lower().replace(" ", "-")


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    css_chunks: list[str] = [
        "/* Self-hosted Google Fonts, regenerated by scripts/fetch_fonts.py */\n"
    ]

    for family, weights in FONTS.items():
        print(f"[fetch] {family} ({', '.join(map(str, weights))})")
        css = http_get(build_request_url(family, weights)).decode("utf-8")

        # Cache (url -> local filename). Variable fonts return one file for
        # all weights, so we download it at most once per unique URL.
        downloaded: dict[str, str] = {}

        for weight in weights:
            block_re = re.compile(
                rf"@font-face\s*{{[^}}]*?font-weight:\s*{weight}\s*;[^}}]*?}}",
                re.DOTALL,
            )
            blocks = block_re.findall(css)
            if not blocks:
                print(f"  ! no @font-face for weight {weight}", file=sys.stderr)
                continue
            block = blocks[-1]  # latin subset (last block in latin-only request)

            woff2_match = re.search(r"url\((https://[^)]+\.woff2)\)", block)
            if not woff2_match:
                print(f"  ! no woff2 url for weight {weight}", file=sys.stderr)
                continue
            woff2_url = woff2_match.group(1)

            if woff2_url in downloaded:
                filename = downloaded[woff2_url]
            else:
                filename = f"{slug(family)}-{weight}.woff2"
                (OUT_DIR / filename).write_bytes(http_get(woff2_url))
                downloaded[woff2_url] = filename
                print(f"  -> {filename}")

            local_block = re.sub(
                r"url\(https://[^)]+\.woff2\)",
                f"url('/static/fonts/{filename}')",
                block,
            )
            css_chunks.append(local_block + "\n")

    (OUT_DIR / "fonts.css").write_text("\n".join(css_chunks), encoding="utf-8")
    print(f"\nWrote {OUT_DIR / 'fonts.css'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
